apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresstest-ping
spec:
  selector:
    matchLabels:
      run: stresstest-ping
  replicas: 1
  template:
    metadata:
      labels:
        run: stresstest-ping
        security: S1
    spec:
      containers:
        - name: stresstest-ping
          image: containerstack/cpustress
          args:
            - --cpu=2
            - --timeout=4800s
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m