apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingjava-manager
  namespace: system
  labels:
    control-plane: pingjava-manager
spec:
  selector:
    matchLabels:
      control-plane: pingjava-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: pingjava-manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: persundecern/pingjava-operator:latest
          name: manager
      terminationGracePeriodSeconds: 10